### ISSUE TITLE
User Story - Recording pain each day via webapp

### ISSUE THREAD

**Issue by gsw-codes** [coding-cohort/Pain-Monitoring-Web-Apps#13]
User Story: As a user, I would like to be able to record my pain level each day via web-app as I am not always able to use my google voice assistant.

Acceptance criteria: 
Webapp must be built using HTML, CSS & Javascript
Webapp must be responsive (mobile/iPad/Desktop) - using standard frameworks, for example, Flexbox, SASS etc
Webapp must have been tested in Lighthouse and pass performance-based criteria.

DoD
Have had a code review.
Have been tested.
Be immediately deployable.

Awaiting updated designs.

**Comment by ug2454** [comment]
can i be assigned to this.

**Comment by gsw-codes** [comment]
@ug2454 yes! we need to tackle the design first however I will create a separate issue (task) for that later today. I will also update the acceptance criteria etc

**Comment by ug2454** [comment]
> @ug2454 yes! we need to tackle the design first however I will create a separate issue (task) for that later today. I will also update the acceptance criteria etc

sure

**Comment by gsw-codes** [comment]
@ug2454 i think this is a duplicate
