### ISSUE TITLE
User Story - Updating account via webapp

### ISSUE THREAD

**Issue by gsw-codes** [coding-cohort/Pain-Monitoring-Web-Apps#15]
User Story: As a user, I want to be able to update my account details so that I can maintain access to my account long time.

Acceptance criteria
Must be possible for the user to update their email address, change the password and other account details.
Webapp must be built using HTML, CSS (& Javascript)
Webapp must be responsive (mobile/iPad/Desktop) - using standard frameworks, for example, Flexbox, SASS etc
Webapp must have been tested in Lighthouse and pass performance-based criteria.

DoD
Have had a code review.
Have been tested.
Be immediately deployable.

Please refer to design layouts for details.

**Comment by VijayKumarKTG** [comment]
I can help out with this too

**Comment by gsw-codes** [comment]
@VijayKumarKTG can you add a comment to #24? the design is done now which i have added to the issue
