### ISSUE TITLE
Design: Sign Up Form

### ISSUE THREAD

**Issue by gsw-codes** [coding-cohort/Pain-Monitoring-Web-Apps#18]
Create a design layout based on the landing page design for the sign-up page.

Acceptance Criteria:
It must include the following form fields:
Name:
Surname:
Email:
Password:

It must meet colour contrast requirements
Design must be consistent across all layouts including the following:
Placement and sizing of all components across screens.
Text that is consistent, spelt correctly and legible.
Images and icons that are appropriate and consistent.
It must not include design elements which will affect load times and performance.
It must be responsive. Please indicate changes for any elements that need to be hidden in case of use on a mobile device.
It will be coded in HTML, CSS and JavaScript. There will not be any use of mobile frameworks in the first release version.
So components design needs to take this into account.
Also colour contrasts as per usability guidelines.
Please refer to the following issues which include design layouts for style approach. 

Design references:
https://github.com/coding-cohort/Pain-Monitoring-Web-Apps/issues/16
https://github.com/coding-cohort/Pain-Monitoring-Web-Apps/issues/6

See also issue #12 
![Screenshot 2020-06-29 at 22 09 23](https://user-images.githubusercontent.com/67404282/86256740-f65eb580-bbb8-11ea-8d92-05ab7a14e9ad.png)

**Comment by VijayKumarKTG** [comment]
I would like to contribute you with this part if you assign me to this. 😁😄

**Comment by Aiyush99** [comment]
i would like to contribute with you in this issue

**Comment by gsw-codes** [comment]
@Aiyush99 @VijayKumarKTG I will put up the design files, please co-ordinate with Uday and comment on the other design tasks so i can assign.

**Comment by DonatellaC** [comment]
I also would like to contribute in this issue :)

**Comment by diomededavid** [comment]
I would like to contribute to the issue for design.

**Comment by gsw-codes** [comment]
@VijayKumarKTG @diomededavid i have created a design for this, for the sake of speed. Please see other issues for design requirements.
