### ISSUE TITLE
Design: Input Pain Levels

### ISSUE THREAD

**Issue by gsw-codes** [coding-cohort/Pain-Monitoring-Web-Apps#20]
Design layout for inputting pain levels every day.

Acceptance criteria
It must be possible to add pain level between 1 and 10.
it must be possible to save the pain level.
It must be appropriate and easy to use for people with limited motor skills and poor eyesight.
It must be possible to easily exit the screen back to the pain reporting screen.

It must meet colour contrast requirements
The design must be consistent across all layouts including the following:
Placement and sizing of all components across screens.
Text that is consistent, spelt correctly and legible.
Images and icons that are appropriate and consistent.
It must not include design elements which will affect load times and performance.
It must be responsive. Please indicate changes for any elements that need to be hidden in case of use on a mobile device.
It will be coded in HTML, CSS and JavaScript. There will not be any use of mobile frameworks in the first release version.
So components design needs to take this into account.

- Please note - one of the mobile size design layouts shows a dial - if this is difficult to implement without mobile components then the design must be modified to not include this. We will consider features like that when the mobile version is started. I suggest reading through this first.
https://www.uxbooth.com/articles/accessibility-visual-design/

Also colour contrasts as per usability guidelines.

Design references:
#16
#6

**Comment by ug2454** [comment]
for this do you have design refernce for web-app? i can only see for mobile version

**Comment by gsw-codes** [comment]
@ug2454 jepp re-read the comments above #16 i have only put down the landing page layout the other pages need design layouts see the mobile version for a guide.

**Comment by diomededavid** [comment]
I can contribute to the design.
