### ISSUE TITLE
Design: Update user account

### ISSUE THREAD

**Issue by gsw-codes** [coding-cohort/Pain-Monitoring-Web-Apps#21]
Create a design layout for updating the user's account. 

Acceptance criteria
It must be appropriate and easy to use for people with limited motor skills and poor eyesight.
It must be possible to easily exit the screen back to the main home screen.

It must meet colour contrast requirements
The design must be consistent across all layouts including the following:
Placement and sizing of all components across screens.
Text that is consistent, spelt correctly and legible.
Images and icons that are appropriate and consistent.
It must not include design elements which will affect load times and performance.
It must be responsive. Please indicate changes for any elements that need to be hidden in case of use on a mobile device.
It will be coded in HTML, CSS and JavaScript. There will not be any use of mobile frameworks in the first release version.
So components design needs to take this into account.
Also colour contrasts as per usability guidelines.

Design references:
#16
#6

**Comment by VijayKumarKTG** [comment]
I would also like to contribute to this one @gsw-codes

**Comment by gsw-codes** [comment]
@VijayKumarKTG could you have a look at #24 with @ JoeWarnerDev? I have put a first try at the design will need to update the interaction model
