### ISSUE TITLE
Design: Review landing page

### ISSUE THREAD

**Issue by gsw-codes** [coding-cohort/Pain-Monitoring-Web-Apps#22]
I have created a design for the landing page but this needs to be reviewed against any changes and other design layouts and the following critieria:

Acceptance criteria
It must be appropriate and easy to use for people with limited motor skills and poor eyesight.
It must be possible to easily exit the screen back to the main home screen. See original mockups.

It must meet colour contrast requirements
The design must be consistent across all layouts including the following:
Placement and sizing of all components across screens.
Text that is consistent, spelt correctly and legible.
Images and icons that are appropriate and consistent.
It must not include design elements which will affect load times and performance.
It must be responsive. Please indicate changes for any elements that need to be hidden in case of use on a mobile device.
It will be coded in HTML, CSS and JavaScript. There will not be any use of mobile frameworks in the first release version.
So components design needs to take this into account.
Also colour contrasts as per usability guidelines.

Design references:
#16
#6

**Comment by Nlparra** [comment]
i dont mind doing the review

**Comment by gsw-codes** [comment]
@Nlparra Once the designs and interaction model is finished I will need someone to go through and review all the design and interaction to ensure it's consistent etc. Suggest you could team up with one of the other developers for this.
